version: '3.8'

services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
  app:
    build: .
    ports:
      - '17000:3000'
    depends_on:
      - db
    links:
      - db
    environment:
      DATABASE_URL: 'postgres://postgres:pass@db:5432/postgres'
